name: Tests
on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!*.md'

  pull_request:
    paths:
      - '**'
      - '!*.md'

  schedule:
    - cron: '0 1 * * *'

jobs:
  tests:
    name: Test GEP on ${{ matrix.images }} (${{ matrix.runner == 'ubuntu-24.04-arm' && 'aarch64' || 'x86_64' }})
    strategy:
      fail-fast: false
      matrix:
        images: [ubuntu24.04, ubuntu22.04, arch]
        runner: [ubuntu-24.04, ubuntu-24.04-arm]
        exclude:
          - images: arch
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker-container
        driver-opts: network=host

    - name: Build ${{ matrix.images }}
      uses: docker/bake-action@v6
      with:
        targets: ${{ matrix.images }}
        set: |
          *.cache-from=type=gha,scope=${{ matrix.images }}-${{ matrix.runner }}
          *.cache-to=type=gha,mode=max,scope=${{ matrix.images }}-${{ matrix.runner }}
        load: true

    - name: Test on ${{ matrix.images }}
      run: docker compose run ${{ matrix.images }} ./tests.sh
