name: Test GEP on different platforms
on: [push, pull_request]

jobs:
  docker:
    strategy:
      fail-fast: false
      matrix:
        images: [ubuntu22.04] # TODO: Add more targets here

    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4

    - name: Docker Build ${{ matrix.images }}
      run: docker-compose build ${{ matrix.images }}

    - name: Test on ${{ matrix.images }}
      run: docker-compose run ${{ matrix.images }} ./tests.sh
